apiVersion: v1
kind: Deployment
metadata: 
  name: app2

  labels: 
    name: app2


spec: 
  replicas: 2
  selectors: 
    matchLabels: 
      name: app2

  template: 
    metadata: 
      labels: 
        name: app2 

    spec: 
      containers: 
      - name: app2 
        image: pushpa4/app2:1.0.0
        ports: 
        - containerPort: 80 


---        




